name: 'Read YAML Action'
description: 'Read yaml file and convert to json'
author: 'Quang Vo'
inputs:
  file_path:
    required: true
    description: 'relative file path to read'
runs:
  using: 'node16'
  main: 'dist/index.js'
